version: '3.4'

services:
  api:
    container_name: api_dev
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    image: api_container_dev
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    restart: always
    depends_on:
      - database
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    links:
      - database
    command: npm run dev

  database:
    image: postgres
    container_name: database_prod
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    env_file:
      - .env
    ports: 
      - ${DB_PORT}:5432
