version: '3.4'

services:
  api:
    build:
      context: .
      target: production
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    restart: always
    depends_on:
      - database
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    command: npm run start

  database:
    image: postgres
    container_name: database_prod
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    env_file:
      - .env
    ports: 
      - ${DB_PORT}:5432
