version: '3.4'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    restart: always
    depends_on:
      - database
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    command: npm run dev

  database:
    image: postgres
    container_name: database
    restart: always
    env_file:
      - .env
    ports: 
      - ${DB_PORT}:5432
