version: '3.4'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    env_file:
      - .env
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports: 
      - ${DB_PORT}:5432
      - 9229:9229

  api:
    container_name: api_dev
    build:
      args:
          - DB_DIALECT=postgres
          - NODE_ENV=development
      context: .
      dockerfile: Dockerfile
      target: development
    image: api_dev
    entrypoint: ["/bin/sh", "./scripts/entrypoint_dev.sh"]
    volumes:
      - ./src/database:/usr/src/app/src/database
      - ./src/scripts:/usr/src/app/scripts
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/build
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - DB_DIALECT=postgres
    restart: always
    depends_on:
      - db
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
