version: '3.4'

services:
  socialmediajwtrestapi:
    image: node:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      env_file:
        - .env
    ports:
      - ${DB_PORT}:${DB_PORT}
