version: '3.4'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    env_file:
      - .env
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports: 
      - ${DB_PORT}:5432

  api_prod:
    container_name: api_prod
    build:
      args:
        - DB_DIALECT=postgres
        - NODE_ENV=production
      context: .
      dockerfile: Dockerfile
      target: production
    image: api_prod
    entrypoint: ["/bin/sh", "./scripts/entrypoint.sh"]
    volumes:
      - ./src/database:/usr/src/app/src/database
      - ./build:/usr/src/app/build
      - ./src/scripts:/usr/src/app/scripts
      - /usr/src/app/node_modules
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - DB_DIALECT=postgres
    restart: always
    depends_on:
      - db
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
